- name: mysql | install
  action: apt pkg=mysql-server

- name: mysql | change root users password
  mysql_user: name={{ mysql_user }} password={{ mysql_pass }}
  when: mysql_user == 'root'

- name: mysql | add the ~/.my.cnf file (for root)
  template: src=templates/mysql-mycnf.j2 dest=~/.my.cnf owner=vagrant group=vagrant
  when: mysql_user == 'root'

- name: mysql | create database {{ mysql_database }}
  mysql_db: db={{ mysql_database }} state=present

- name: mysql | create user {{ mysql_user }}
  mysql_user: name={{ mysql_user }} password={{ mysql_pass }} priv={{ mysql_database }}.*:ALL
  when: mysql_user != 'root'

- name: mysql | start/restart
  command: service mysql restart