- name: php | add php.ini
  template: src=templates/php-ini.j2 dest=/etc/php5/apache2/php.ini

- name: php | install packages
  apt: pkg={{ item }}
  with_items:
    - php5
    - php5-dev
    - php-pear
    - php5-mysql
    - php5-curl
    - php5-mcrypt
    - php5-gd
    - php5-sqlite
    - libpcre3-dev

- name: php | install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin

- name: php | rename composer.phar to composer
  command: mv /usr/local/bin/composer.phar /usr/local/bin/composer

- name: php | pear | update
  command: pear upgrade

- name: php | pear | auto-discover
  command: pear config-set auto_discover 1

- name: php | pear | add necessary channels
  command: pear channel-discover {{ item }}
  ignore_errors: yes
  with_items:
    - pear.phpunit.de
    - pear.symfony.com

- name: php | pear | install phpunit
  ignore_errors: yes
  command: pear install pear.phpunit.de/PHPUnit

- name: php | pecl | test for previous xdebug install
  shell: pecl list | grep -i 'xdebug' || true
  register: php_pecl_xdebug_exists

- include: php/xdebug.yml
  when: '{{ use_xdebug }}'