- name: www | add users to www-data group
  user: name={{ item }} groups=www-data append=yes
  with_items:
    - root
    - vagrant
    - www-data

- name: www | create /var/www/ directory
  file: path=/var/www/ group=www-data mode=775 owner=vagrant state=directory

- name: www | add an /etc/hosts entry for {{ site_name }}
  lineinfile: dest=/etc/hosts insertafter=EOF regexp="127\.0\.0\.1\s+{{ item }}"  line="127.0.0.1 {{ item }}"
  with_items:
    - '{{ site_name }}'
    - www.{{ site_name }}