- name: php | xdebug | install
  command: pecl install xdebug
  when: ${php_pecl_xdebug_exists.stdout} == ''

- name: php | xdebug | fetch php extension dir
  shell: php -i | grep -i "^extension_dir" | sed -E 's/.+?=>\s+//'
  register: php_extension_dir

- name: php | xdebug | add config
  template: src=templates/php-xdebug.j2 dest=/etc/php5/conf.d/xdebug.ini

- name: php | xdebug | check if path exists
  stat: path={{ mnt_dir }}/webgrind
  register: webgrind_exists

- name: php | xdebug | download webgrind
  git: dest={{ mnt_dir }}/webgrind repo=https://github.com/jokkedk/webgrind.git
  when: not webgrind_exists